apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  defaultBackend: # сервис на который будет уходить трафик по умолчания
    service:
      name: {{ .Release.Name }}-service
      port:
        number: 80
  rules:
    - host: fake.myaddress.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 80
